name: cf-syslog-drain

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: cf-syslog-drain
  version: latest
- name: loggregator
  version: latest
- name: consul
  version: latest

instance_groups:
- name: consul
  azs:
  - z1
  instances: 1
  persistent_disk_type: 1GB
  vm_type: minimal
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: consul_agent
    release: consul
    consumes:
      consul: nil
      consul_common: {from: consul_common_link}
      consul_server: {from: consul_server_link}
      consul_client: {from: consul_client_link}
    provides:
      consul_common: {as: consul_common_link, shared: true}
      consul_server: {as: consul_server_link, shared: true}
      consul_client: {as: consul_client_link, shared: true}
    properties:
      consul:
        agent:
          mode: server
          domain: cf.internal
        require_ssl: true
        encrypt_keys:
        - "((consul_encrypt_key))"
        agent_cert: "((consul_agent.certificate))"
        agent_key: "((consul_agent.private_key))"
        ca_cert: "((consul_server.ca))"
        server_cert: "((consul_server.certificate))"
        server_key: "((consul_server.private_key))"
  update:
    serial: true
    max_in_flight: 1

- name: adapter
  azs:
  - z1
  - z2
  instances: 3
  persistent_disk_type: 1GB
  vm_type: minimal
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: consul_agent
    release: consul
    consumes:
      consul: nil
      consul_common: {from: consul_common_link}
      consul_server: {from: consul_server_link}
      consul_client: {from: consul_client_link}
  - name: adapter
    release: cf-syslog-drain
    properties:
      scalablesyslog:
        adapter:
          tls:
            ca: "((adapter_tls.ca))"
            cert: "((adapter_tls.certificate))"
            key: "((adapter_tls.private_key))"
            cn: ss-adapter
        adapter_rlp:
          tls:
            ca: "((adapter_rlp_tls.ca))"
            cert: "((adapter_rlp_tls.certificate))"
            key: "((adapter_rlp_tls.private_key))"
            cn: reverselogproxy
  - name: metron_agent
    release: loggregator
    properties: &metron_agent_properties
      metron_agent:
        deployment: "((system_domain))"
      metron_endpoint:
        shared_secret: "((dropsonde_shared_secret))"
      loggregator:
        tls:
          ca_cert: "((loggregator_tls_metron.ca))"
          metron:
            cert: "((loggregator_tls_metron.certificate))"
            key: "((loggregator_tls_metron.private_key))"

- name: scheduler
  azs:
  - z1
  instances: 1
  persistent_disk_type: 1GB
  vm_type: minimal
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: consul_agent
    release: consul
    consumes:
      consul: nil
      consul_common: {from: consul_common_link}
      consul_server: {from: consul_server_link}
      consul_client: {from: consul_client_link}
  - name: scheduler
    release: cf-syslog-drain
    properties:
      scalablesyslog:
        scheduler:
          require_opt_in: false
          api:
            url: https://cloud-controller-ng.service.cf.internal:9023
          tls:
            client:
              ca: "((scheduler_client_tls.ca))"
              cert: "((scheduler_client_tls.certificate))"
              key: "((scheduler_client_tls.private_key))"
              adapter_cn: "ss-adapter"
            api:
              ca: "((scheduler_api_tls.ca))"
              cert: "((scheduler_api_tls.certificate))"
              key: "((scheduler_api_tls.private_key))"
              cn: "cloud-controller-ng.service.cf.internal"
  - name: metron_agent
    release: loggregator
    properties: *metron_agent_properties

variables:
- name: loggregator_ca
  type: certificate
  options:
    is_ca: true
    common_name: CA
- name: adapter_rlp_tls
  type: certificate
  options:
    ca: loggregator_ca
    common_name: ss-adapter-rlp
    extended_key_usage:
    - client_auth
    - server_auth
- name: scheduler_api_tls
  type: certificate
  options:
    ca: loggregator_ca
    common_name: cloud-controller-ng.service.cf.internal
    extended_key_usage:
    - client_auth
    - server_auth
- name: adapter_tls
  type: certificate
  options:
    ca: loggregator_ca
    common_name: ss-adapter
    extended_key_usage:
    - server_auth
    - client_auth
- name: scheduler_client_tls
  type: certificate
  options:
    ca: loggregator_ca
    common_name: ss-scheduler
    extended_key_usage:
    - client_auth
- name: loggregator_tls_metron
  type: certificate
  options:
    ca: loggregator_ca
    common_name: metron
    extended_key_usage:
    - client_auth
    - server_auth
- name: consul_encrypt_key
  type: password
- name: consul_agent_ca
  type: certificate
  options:
    is_ca: true
    common_name: consulCA
- name: consul_agent
  type: certificate
  options:
    ca: consul_agent_ca
    common_name: consul_agent
    extended_key_usage:
    - client_auth
    - server_auth
- name: consul_server
  type: certificate
  options:
    ca: consul_agent_ca
    common_name: server.dc1.cf.internal
    extended_key_usage:
    - client_auth
    - server_auth

update:
  canaries: 10
  max_in_flight: 10
  canary_watch_time: 30000-60000
  update_watch_time: 5000-60000
  serial: true
