#!/usr/bin/env bash

bosh create-release --force
bosh -e lite upload-release --rebase
bosh -e lite deploy manifests/scalable-syslog.yml -n -d scalablesyslog -o manifests/fake-ops.yml --vars-store /tmp/vars.yml
