#!/bin/sh

set -e

if [ "$1" = "" ] || [ "$2" = "" ] || [ "$3" = "" ] || [ "$4" = "" ]; then
    echo "usage: $0 <bbs-ca.crt> <bbs-ca.key> <loggregator-ca.crt> <loggregator-ca.key>"
    echo "       $0 no-ca"
    exit 1
fi

# Place keys and certificates here
depot_path="scalable-syslog-certs"
mkdir -p "$depot_path"

# CA to distribute to scalable-syslog certs
certstrap --depot-path "$depot_path" init --passphrase '' --common-name scalable-syslog-ca

# Install certstrap
go get -v github.com/square/certstrap

bbs_ca_cert_path=$1
bbs_ca_key_path=$2
bbs_ca_name=$(basename "$bbs_ca_cert_path" ".crt")
ln -s "$bbs_ca_cert_path" "$depot_path"/
ln -s "$bbs_ca_key_path" "$depot_path"/

loggregator_ca_cert_path=$3
loggregator_ca_key_path=$4
loggregator_ca_name=$(basename "$loggregator_ca_cert_path" ".crt")
ln -s "$loggregator_ca_cert_path" "$depot_path"/
ln -s "$loggregator_ca_key_path" "$depot_path"/

# Scheduler certificate (to communicate with adapter)
certstrap --depot-path "$depot_path" request-cert --passphrase '' --common-name ss-scheduler
certstrap --depot-path "$depot_path" sign ss-scheduler --CA scalable-syslog-ca

# Scheduler API certificate (cert used to communicate with API to fetch
# syslog drain bindings
certstrap --depot-path "$depot_path" request-cert --passphrase '' --common-name ss-scheduler-cc
certstrap --depot-path "$depot_path" sign ss-scheduler-cc --CA "$bbs_ca_name"

# Adapter certificate (to communicate with scheduler)
certstrap --depot-path "$depot_path" request-cert --passphrase '' --common-name ss-adapter
certstrap --depot-path "$depot_path" sign ss-adapter --CA scalable-syslog-ca

# Adapter RLP certificate (cert used to communicate with Reverse Logging Proxy)
certstrap --depot-path "$depot_path" request-cert --passphrase '' --common-name ss-adapter-rlp
certstrap --depot-path "$depot_path" sign ss-adapter-rlp --CA "$loggregator_ca_name"
