#!/bin/sh

set -e

# Place keys and certificates here
depot_path="certs"
mkdir -p "$depot_path"

# Install certstrap
go get -v github.com/square/certstrap

# Loggregator CA
certstrap --depot-path ${depot_path} init --passphrase '' --common-name loggregatorCA --expires "25 years"

# Adapter CA
certstrap --depot-path ${depot_path} init --passphrase '' --common-name scalableSyslogCA --expires "25 years"

# Scheduler certificate (to communicate with adapter)
certstrap --depot-path "$depot_path" request-cert --passphrase '' --common-name scheduler
certstrap --depot-path "$depot_path" sign scheduler --CA "scalableSyslogCA" --expires "25 years"

# Scheduler CAPI certificate (cert used to communicate with API to fetch
# syslog drain bindings
certstrap --depot-path "$depot_path" request-cert --passphrase '' --common-name scheduler-api
certstrap --depot-path "$depot_path" sign scheduler-api --CA "scalableSyslogCA" --expires "25 years"

# Adapter certificate (to communicate with scheduler)
certstrap --depot-path "$depot_path" request-cert --passphrase '' --common-name adapter
certstrap --depot-path "$depot_path" sign adapter --CA "scalableSyslogCA" --expires "25 years"

# Adapter RLP certificate (cert used to communicate with Reverse Logging Proxy)
certstrap --depot-path "$depot_path" request-cert --passphrase '' --common-name adapter-rlp
certstrap --depot-path "$depot_path" sign adapter-rlp --CA "loggregatorCA" --expires "25 years"

# Fake Log Provider
certstrap --depot-path "$depot_path" request-cert --passphrase '' --common-name fake-log-provider
certstrap --depot-path "$depot_path" sign fake-log-provider --CA "loggregatorCA" --expires "25 years"
